### PR TITLE
Omit the version number from headers and HTML responses

### LINKED ISSUE #542: Option to disable disclosure of version via header and templates?
e.g. https://github.com/tinyproxy/tinyproxy/blob/72b93f6d4b598a1f809f4e5ff383757c52fa9765/src/utils.c#L42 and https://github.com/tinyproxy/tinyproxy/blob/72b93f6d4b598a1f809f4e5ff383757c52fa9765/src/html-error.c#L202

For example, Apache has [ServerTokens Prod](https://httpd.apache.org/docs/2.4/mod/core.html#servertokens) and nginx has [server_tokens off;](https://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens).

When getting cybersecurity insurance, for example, the insurer often uses an automated service to check for vulnerabilities, and Ubuntu, Debian, etc. do not update version numbers after patching, therefore the service reports false positives and the insurer then wants to increase premiums, unless the insured goes through the process of getting those false positives removed. A much simpler solution is to prevent those automated services from raising false positives to begin with, by not disclosing tinyproxy's version.

### PR DESCRIPTION
**Pull request by jpmckinney**
closes #542

I haven't written C or Perl in over a decade, but I think I got it (assuming tests pass).

I don't know what effect this line has, so I left it:

https://github.com/tinyproxy/tinyproxy/blob/72b93f6d4b598a1f809f4e5ff383757c52fa9765/src/html-error.c#L277

Edit: Aha, I think this fills in the version variable in the HTML templates. I can delete the `{version}` from the HTML templates and leave this variable (in case users want to customize the templates to add the version back) – or I can delete both (meaning users can't restore the variable), or I can not do anything (requiring users to edit templates to prevent disclosure of the version).

### CODE REVIEW

**Comment by rofl0r** [comment]
> I can delete the {version} from the HTML templates and leave this variable (in case users want to customize the templates to add the version back)

that sounds like the best option, indeed.
i'm gonna click on approve already so the CI test kicks in on the changes you've already done.

**Comment by jpmckinney** [comment]
Cool, I made the commit :)

**Comment by jpmckinney** [comment]
Thanks @rofl0r  - just curious what the release cadence is?

**Comment by rofl0r** [comment]
a click on the releases tab should answer your question. it's typically > 12 months.

**Pull request merged**
