### PR TITLE
Enable tinyproxy packaging as a snap.

### PR DESCRIPTION
**Pull request by adglkh**
This PR enable tinyproxy to package as a snap. Also added conditional
for snap packaging by testing "--enable-snap". The reason here for
'--enable-snap' is that all services run as root thanks to confinement
in snap world and regarding system call(setuid, setgid) will trigger
apparmor "DENIED" error when running tinyproxy snap in confined mode.
Please refer to syslog here http://paste.ubuntu.com/24063282/.

### CODE REVIEW

**Comment by adglkh** [comment]
This PR is still using the master branch as tinyproxy-snap source in snapraft.yaml file. 
As a PR, I don't change it as it targets to merge into master.
You can simply make a change as following to use my branch(snap-package) for testing purpose for the time being.
http://paste.ubuntu.com/24063358/

Thanks

**Comment by rofl0r** [comment]
maintaining 3rd party build/configuration infrastructure in the official source code repo looks like a bad idea to me. once you have snap infrastructure in there, debian maintainer will show up and demand his debian packages script to be integrated. then gentoo, fedora, suse, etc will follow, and in the end you spend 90% of your time maintaining it.

**Comment by elopio** [comment]
I think that the benefits of having a snapcraft.yaml in the main branch outweight the drawbacks by far. You could easily hook it into travis, launchpad or any other CI system to have releases to the edge channel on the store for every change in master. That will make your early adopters very happy, and you will get plenty of feedback from the ubuntu community of testers before a stable release.

In addition to that, the snaps you release to the stable channel will be available to all the ubuntu users in trusty and xenial, who are left behind with old versions in the archive.

**Comment by obnoxxx** [comment]
I agree that it seems kind of weird to put such a big amount of packaging content into the code repository. Generally, the packaging content is a distribution-specific add-on, imho, and I am still making up my mind if I think we should have it in the code repo at all.

(Apart from this: what is a "snap" -- never heard of that... :-} )

Regarding the actual code changes: 
* The templated conf file confuses me. Why can't you use the configure's .conf.in --> .conf mechanism? This is also a maintenance nightmare because it would require us to maintain both tinyproxy.conf.in *and* tinyproxy.conf.template.
* The mechanism with run-tinyproxy and settings seems incredibly fragile: for instance, settings references explicit lines in the conf file. I.e. this needs to manually adapted when the config file chances. Maintenance nightmare again. Also this is just an example config file.
* The code change to prevent change_user is not good in that it is snap-specific and a compile-time change. I'd much rather support a mechanism that enables this behavior at runtime without specific reference to snap. E.g. prevent change_user when user:group is set to root:root in the config.

As a summary, I am not inclined to take this PR, and think this packaging should be in a separate snap-specific packaging repo (due to the maintenance nightmare). But I am willing to accommodate for any code/config changes that are needed in order to enable it. (But more generically, as suggested above.)

**Pull request closed without merging**
