### PR TITLE
Continue with forward proxy if ReverseOnly is not true and no mapping available

### PR DESCRIPTION
**Pull request by sleemburg**
Hi,

As indicated by Michael Adam, I changed the patch code and resubmit the pull request.

Kind regards,
Stephan

### CODE REVIEW

**Comment by sleemburg** [comment]
Sorry, I'm closing this request and will create a new one from a clean source tree.

**Comment by obnoxxx** [comment]
@sleemburg: there is no need to create new pull requests! you can do changes with the branch locally `git rebase -i origin/master` and then push over your branch forcerfully: 'git push <your-git-remote> <branchname> --force`. This will update the pull request with the latest patchset. This way we can take a couple of turns reviewing and working on the patchset staying with the discussion in one place. Makes sense?

**Comment by sleemburg** [comment]
Hi Michael,

Sorry, I am stil not good with git..

What you say makes sense.

Sorry for any inconvenience.

Kind regards,

Stephan

**Comment by obnoxxx** [comment]
No worries, I just want to share what I think is the most convenient workflow. Thanks for contributing!

**Pull request closed without merging**
