### PR TITLE
add support for basic HTTP authentication

### PR DESCRIPTION
**Pull request by rofl0r**
using the "BasicAuth" keyword in tinyproxy.conf.

base64 code was written by myself and taken from my own library "libulz".
for this purpose it is relicensed under the usual terms of the tinyproxy
license.

### CODE REVIEW

**Comment by jeroenvermeulen** [comment]
Tested it by building from this branch: https://github.com/rofl0r/tinyproxy/tree/auth4
I used the Proxy settings from macOS High Siera, via the Network configuration. I configured both HTTP and HTTPS proxy.
It was *not* working when I added the line `BasicAuth myuser mypass` to the config.
Tinyproxy log:
```
CONNECT   Dec 28 22:31:46 [21835]: Connect (file descriptor 9): vpnclient-l2tp-1.redlan [10.200.70.221]
CONNECT   Dec 28 22:31:46 [21835]: Request (file descriptor 9): GET http://watismijnip.nl/ HTTP/1.1
INFO      Dec 28 22:31:46 [21835]: no entity
```

**Comment by rofl0r** [comment]
thanks for testing.
could you please apply this patch (which improves logging) https://0x0.st/s8FU.patch

and then provide full output of log.

this is my config: https://0x0.st/s8Fk.conf

i run it like this in a terminal:
```
 src/tinyproxy -d -c tinyproxy.conf
```

i get this output when starting up (using the above patch):
```
INFO      Dec 28 23:13:57 [23284]: Initializing tinyproxy ...
INFO      Dec 28 23:13:57 [23284]: Reloading config file
INFO      Dec 28 23:13:57 [23284]: Setting "Via" header to 'tinyproxy'
INFO      Dec 28 23:13:57 [23284]: Added basic auth user : user
INFO      Dec 28 23:13:57 [23284]: Added basic auth user : admin
WARNING   Dec 28 23:13:57 [23284]: User / pass in basicauth rule too long
...
```
then i switch to another terminal and test connectivity like this:

```
$ http_proxy=http://user:pass@localhost:8888 curl ifconfig.me
192.57.34.201

$ http_proxy=http://user:wrongpass@localhost:8888 curl ifconfig.me
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
<head><title>403 Access denied</title></head>
<body>
<h1>Access denied</h1>
<p>The administrator of this proxy has not configured it to service requests from you.</p>
<hr />
<p><em>Generated by tinyproxy version 1.9.0.</em></p>
</body>
</html>
```

seems to work here.

**Comment by suntong** [comment]
looking forward to the merge.

**Comment by jeroenvermeulen** [comment]
@rofl0r I did test with your patch 

I works when I use `curl`:
```
CONNECT   Dec 30 21:08:33 [30095]: Connect (file descriptor 9): vpnclient-l2tp-1.redlan [10.200.70.221]
CONNECT   Dec 30 21:08:33 [30095]: Request (file descriptor 9): GET http://ifconfig.me/ HTTP/1.1
INFO      Dec 30 21:08:33 [30095]: No upstream proxy for ifconfig.me
INFO      Dec 30 21:08:33 [30095]: opensock: opening connection to ifconfig.me:80
INFO      Dec 30 21:08:33 [30095]: opensock: getaddrinfo returned for ifconfig.me:80
CONNECT   Dec 30 21:08:33 [30095]: Established connection to host "ifconfig.me" using file descriptor 10.
INFO      Dec 30 21:08:35 [30095]: Closed connection between local client (fd:9) and remote client (fd:10)
```

It does not work when I use the macOS High Sierra proxy settings with Basic Auth:
```
CONNECT   Dec 30 21:08:03 [30093]: Request (file descriptor 9): GET http://ifconfig.me/ HTTP/1.1
INFO      Dec 30 21:08:03 [30093]: no entity
CONNECT   Dec 30 21:08:03 [30096]: Connect (file descriptor 9): vpnclient-l2tp-1.redlan [10.200.70.221]
CONNECT   Dec 30 21:08:03 [30087]: Connect (file descriptor 9): vpnclient-l2tp-1.redlan [10.200.70.221]
CONNECT   Dec 30 21:08:03 [30096]: Request (file descriptor 9): GET http://ifconfig.me/favicon.ico HTTP/1.1
INFO      Dec 30 21:08:03 [30096]: no entity
```

It does work when I use the macOS High Sierra proxy settings without Basic Auth, removed both from Tinyproxy config and macOS settings:
```
ERROR     Dec 30 21:11:47 [9241]: read_request_line: Client (file descriptor: 9) closed socket before read.
ERROR     Dec 30 21:11:47 [9242]: read_request_line: Client (file descriptor: 9) closed socket before read.
ERROR     Dec 30 21:11:47 [9241]: Error reading readable client_fd 9
WARNING   Dec 30 21:11:47 [9241]: Could not retrieve request entity
ERROR     Dec 30 21:11:47 [9242]: Error reading readable client_fd 9
WARNING   Dec 30 21:11:47 [9242]: Could not retrieve request entity
CONNECT   Dec 30 21:11:47 [9249]: Connect (file descriptor 9): vpnclient-l2tp-1.redlan [10.200.70.221]
CONNECT   Dec 30 21:11:47 [9248]: Connect (file descriptor 9): vpnclient-l2tp-1.redlan [10.200.70.221]
CONNECT   Dec 30 21:11:47 [9248]: Request (file descriptor 9): GET http://ifconfig.me/ HTTP/1.1
INFO      Dec 30 21:11:47 [9248]: No upstream proxy for ifconfig.me
INFO      Dec 30 21:11:47 [9248]: opensock: opening connection to ifconfig.me:80
CONNECT   Dec 30 21:11:47 [9242]: Connect (file descriptor 9): vpnclient-l2tp-1.redlan [10.200.70.221]
INFO      Dec 30 21:11:47 [9248]: opensock: getaddrinfo returned for ifconfig.me:80
CONNECT   Dec 30 21:11:47 [9241]: Connect (file descriptor 9): vpnclient-l2tp-1.redlan [10.200.70.221]
```

**Comment by rofl0r** [comment]
@jeroenvermeulen thanks. do you think you could run wireshark in the background, listening on your loopback device, while making the connection with your macOS program ?
then we could look at the contents of the packet sent to the proxy, and determine what it tries to do.

**Comment by jeroenvermeulen** [comment]
@rofl0r Sorry, that would take a bit too much time to set up, I have some other stuff to do.
You can test using a Macbook or maybe you can repeat the problem using Windows' proxy settings.

**Comment by rofl0r** [comment]
i have neither mac nor windows.

**Comment by natedogith1** [comment]
I can't connect with Firefox's configuration settings.  There's no way to set a password, and I assume Firefox only requests a password on auth failure.

**Comment by natedogith1** [comment]
Changing the error to 407 and adding a Proxy-Authenticate header seems to fix the issue. (not sure if the 407 was necessary, but the Proxy-Authenticate definitely was)

**Comment by rofl0r** [comment]
@natedogith1 interesting. do you have some more details ?

**Comment by natedogith1** [comment]
What sort of details are you looking for?
I change the [403](https://github.com/tinyproxy/tinyproxy/pull/129/files#diff-01f95af871310d95e6f655f7f6385886R1493) to a 407.  I also added an always-sent header of "Proxy-Authenticate: Basic realm=\"TinyProxy\"\r\n" to [html-error.c](https://github.com/tinyproxy/tinyproxy/blob/302738dee5dd247881a4a5eba173f4333dc2a7d4/src/html-error.c#L157) (not the right way to do this, but it worked for a quick test)

**Comment by natedogith1** [comment]
I will test it in firefox, and I think I can get someone to test on a mac again.

**Comment by rofl0r** [comment]
PR branch updated, please test @natedogith1

**Comment by natedogith1** [comment]
Works for me with Firefox, and confirmed it works for mac

**Comment by rofl0r** [comment]
thanks. do you have an opinion on the configuration side of things, or even a better idea on how to integrate the basic auth option into the existing configuration settings ?

**Comment by jeff47** [comment]
Hmm, I am still seeing the "no entity" error using SwitchyOmega.  

I am using tinyproxy 1.10.0-git-29-gd98aabf

**Comment by rofl0r** [comment]
> Hmm, I am still seeing the "no entity" error using SwitchyOmega.

that seems unrelated to this PR. please open a new issue if you think something is wrong.

**Pull request merged**
