### PR TITLE
Prepare the 1.10.0 release

### PR DESCRIPTION
**Pull request by obnoxxx**
Finally :-)

### CODE REVIEW

**Comment by rofl0r** [comment]
LGTM :+1:

**Comment by obnoxxx** [comment]
updated with manpage fix

**Comment by gaheinrichs** [comment]
Thank you for this release! You guys rock. When could we expect this to be available in EPEL repository? Thanks again!

**Comment by obnoxxx** [comment]
@gaheinrichs writes:
> Thank you for this release! You guys rock.

Thanks! :-)

> When could we expect this to be available in EPEL repository? Thanks again!

Which one are you referring to more precisely? The Fedora EPEL repo?
I started working this update into fedora 29 (it's in rawhide already).
I can try to bring it into EPEL.

**Pull request merged**
