### PR TITLE
Add example systemd service and tmpfile.d files.

### PR DESCRIPTION
**Pull request by jmallach**

### CODE REVIEW

**Comment by rofl0r** [comment]
-1. it's not the job of every package that can be used as a service to supply systemd shims. if we start with that, we can as well add service scripts for runit, openrc, sysv init, etc. also if this is added, it will be broken at some point, and ppl will complain, and someone will have to maintain that. and it's well known that systemd changes at the glimpse of an eye.

**Comment by jmallach** [comment]
> if we start with that, we can as well add service scripts for runit, openrc, sysv init, etc.

I say "bring 'em on". It's extras, examples. If you are deploying tinyproxy from scratch and you happen to be the 0.001 running it on runit, an out of the shelve example is welcome, isn't it? In this particular case, systemd is what the vast majority is running or will be running in the next few years, unless you very conciously chose not to.

> it's well known that systemd changes at the glimpse of an eye.

Eh? Nope.

**Comment by rofl0r** [comment]
why do you need to add it to the Makefiles if it's only "examples"?

> systemd is what the vast majority is running

just because the vast majority of lemmings will jump from a cliff doesn't mean you should lead them there and support them in that effort.

anyway systemd scripts is not part of software projects, it's part of the distro maintainers job. if someone needs your example, he'll copy it from your debian package.

**Comment by jmallach** [comment]
@rofl0r, eh I add it to the makefiles so this actually gets included in the tarball?!? Don't worry, it won't infect your Slackware with systemd units, you'll be safe from the infection.

Instead of closing this as stated on IRC, I have simply unsubscribed from the PR, because I really don't have the energy or time to deal with @rofl0r's apparent systemd phobia. Coming from Debian, I know very well how energy draining that can be.

@obnoxxx, feel free to close this PR if it's going to be a problem with other of your contributors, as wacky as their reasoning can be.

kthxbye.

**Pull request closed without merging**
