### PR TITLE
Add regex option for upstream proxy selection

### PR DESCRIPTION
**Pull request by huaraz**
These changes will allow to use a regex for the upstream configuration.

The syntax is regex(<regex>)  for case sensitive basic regular expression
regexi(<regex>)  for case insensitive basic regular expression
regexe(<regex>)  for case sensitive extended regular expression
regexei(<regex>) or  regexie(<regex>) for case insensitive extended regular expression

Markus

### CODE REVIEW

**Comment by rofl0r** [comment]
thanks for your contribution.
please describe in detail what the PR tries to achieve and how the new functionality is supposed to be used. after that, if the changes are considered a worthwhile addition, the PR will need to be redone on current master and all gratuitous whitespace changes you introduced removed, as well as documentation added in the configuration file template and possibly manpage(s).

**Comment by huaraz** [comment]
> thanks for your contribution.
> please describe in detail what the PR tries to achieve and how the new functionality is supposed to be used. after that, if the changes are considered a worthwhile addition, the PR will need to be redone on current master and all gratuitous whitespace changes you introduced removed, as well as documentation added in the configuration file template and possibly manpage(s).

I'll work on the man pages, but I used the provided tinyproxy-indent.sh for whitespacing. indent version was:
indent --version
GNU indent 2.2.11

Markus

**Comment by rofl0r** [comment]
> but I used the provided tinyproxy-indent.sh for whitespacing.

that doesn't matter, we have a policy of "no gratuitous whitespace changes", in order to keep diffs reviewable, and even more importantly, to be able to selectively undo or port changes to different branches.

**Comment by huaraz** [comment]
Will redo

**Pull request closed without merging**
