### PR TITLE
Remove trailing whitespace in conf file

### PR DESCRIPTION
**Pull request by briancain**

### CODE REVIEW

**Comment by obnoxxx** [comment]
Thanks for the patch! @briancain 
I think the intention was to provide a template so that when you uncomment the line you don't have to add the space before adding the log level value.

Maybe we should add a debug level value to the commented out line instead?

**Comment by briancain** [comment]
@obnoxxx - Ah. Sure, that's fair :) My editor doesn't like whitespace (and I know other people configure their editors that way) so I figured it might of just been a mistake. I'm fine with closing this if the whitespace was intentional.

**Comment by obnoxxx** [comment]
@briancain if you would add an example value after the whitespace instead, that would be great!

**Comment by briancain** [comment]
@obnoxxx - Great! I went with `Warning` since it's mid way up the log level settings, and that might be the most helpful for people in general at a quick glance?

**Pull request merged**
