### PR TITLE
Include limits.h to fix build on OSX

### PR DESCRIPTION
**Pull request by centromere**

### CODE REVIEW

**Comment by rofl0r** [comment]
thanks for your PR. could you share the error message you got prior to your fix ?

**Comment by centromere** [comment]
> thanks for your PR. could you share the error message you got prior to your fix ?

```
Now type 'make' to compile Tinyproxy.
➜  tinyproxy git:(master) make
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in src
  CC       hostspec.o
warning: unknown warning option '-Wlogical-op'; did you mean '-Wlong-long'? [-Wunknown-warning-option]
hostspec.c:26:34: error: use of undeclared identifier 'ULONG_MAX'
        if ((errno == ERANGE && mask == ULONG_MAX)
                                        ^
1 warning and 1 error generated.
make[2]: *** [hostspec.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
➜  tinyproxy git:(master)
```

**Comment by obnoxxx** [comment]
I see the same error on macos.
I can confirm this PR is working.
I'll see whether we can add macos to the CI checks...

**Comment by rofl0r** [comment]
thanks, merged as 7168a42 (fixed whitespace).

**Pull request closed without merging**
