### PR TITLE
simplify codebase by using one thread/conn, instead of preforked procs

### PR DESCRIPTION
**Pull request by rofl0r**
the existing codebase used an elaborate and complex approach for
its parallelism:

5 different config file options, namely

- MaxClients
- MinSpareServers
- MaxSpareServers
- StartServers
- MaxRequestsPerChild

were used to steer how (and how many) parallel processes tinyproxy
would spin up at start, how many processes at each point needed to
be idle, etc.
it seems all preforked processes would listen on the server port
and compete with each other about who would get assigned the new
incoming connections.
since some data needs to be shared across those processes, a half-
baked "shared memory" implementation was provided for this purpose.
that implementation used to use files in the filesystem, and since
it had a big FIXME comment, the author was well aware of how hackish
that approach was.

this entire complexity is now removed. the main thread enters
a loop which polls on the listening fds, then spins up a new
thread per connection, until the maximum number of connections
(MaxClients) is hit. this is the only of the 5 config options
left after this cleanup. since threads share the same address space,
the code necessary for shared memory access has been removed.
this means that the other 4 mentioned config option will now
produce a parse error, when encountered.

currently each thread uses a hardcoded default of 256KB per thread
for the thread stack size, which is quite lavish and should be
sufficient for even the worst C libraries, but people may want
to tweak this value to the bare minimum, thus we may provide a new
config option for this purpose in the future.
i suspect that on heavily optimized C libraries such a musl, a
stack size of 8-16 KB per thread could be sufficient.

since the existing list implementation in vector.c did not provide
a way to remove a single item from an existing list, i added my
own list implementation from my libulz library which offers this
functionality, rather than trying to add an ad-hoc, and perhaps
buggy implementation to the vector_t list code. the sblist
code is contained in an 80 line C file and as simple as it can get,
while offering good performance and is proven bugfree due to years
of use in other projects.

### CODE REVIEW

**Comment by rofl0r** [comment]
> Works as expected but the memory footprint is high. A config option for this purpose is recommended..

thanks for testing. could you provide some comparison numbers before/after with the same `MaxClients` setting in the config file ?

btw in src/child.c, there's this block:
```c
                if (pthread_attr_init(&attr) == 0) {
                        attrp = &attr;
                        pthread_attr_setstacksize(attrp, 256*1024);
                }

                if (pthread_create(&child->thread, attrp, child_thread, child) $
                        sblist_delete(childs, sblist_getsize(childs) -1);
                        free(child);
                        goto oom;
                }
```

in the line with `pthread_attr_setstacksize(attrp, 256*1024);`, a stack size of 256 KB is set per client. this value was chosen as a really conservative value that should work on any C library implementation, even the worst. i plan to make this a configurable setting. if you want, you could try out some lower values there, if you're using a musl-libc based linux such as openwrt, a value as low as 8*1024 might be sufficient. going even lower than that could potentially lead to crashes.

**Comment by robertosgm** [comment]
Tested this on MacOS:  

           if (pthread_attr_init(&attr) == 0) {
                        attrp = &attr;
                        pthread_attr_setstacksize(attrp, 256*1024);
                }

                if (pthread_create(&child->thread, attrp, child_thread, child) $
                        sblist_delete(childs, sblist_getsize(childs) -1);
                        free(child);
                        goto oom;
                }

It works with 64*1024 Bytes, it crashes at lower values.

**Comment by harryboo** [comment]
After restart the memory footprint (no matter which setting for 'MaxClients') is:

Old model (StartServers 5) - Virtual memory size (932 kB) - Resident set size (400 kB)
thread - Virtual memory size (1160 kB) - Resident set size (420 kB)

After calling the same URLs from outside the memory footprint for the old model stays the same.
For the threaded model (all measurements with 256kB):

MaxClients		Virtual memory size		Resident set size
20				2468 kB					588 kB
50				2992 kB					636 kB
100				2460 kB					584 kB
150				2732 kB					628 kB
200				2728 kB					604 kB

**Comment by harryboo** [comment]
Sorry i think i have forgotten the worker for the old model. Every worker consumes 940 kB of memory.

**Comment by rofl0r** [comment]
> This means that the footprint of the threaded model is lower than the old model?

yeah, my expectation was that the threaded model would use less memory, if the stacksize is set to a low value and a reasonable MaxClient limit is set, because the old model uses `fork()` which needs a complete copy of the address space of the parent per worker.

**Comment by deba12** [comment]
@rofl0r do you have time frame when will be merged ?

**Comment by rofl0r** [comment]
> @rofl0r do you have time frame when will be merged ?

after sufficient testing. this is a quite intrusive PR and i want to get the details right before merging it into master. results like those from @harryboo are very important to get the full picture.

**Comment by n3mxnet** [comment]
totally awesome!

**Comment by limbo127** [comment]
Hello, 
We have issue with proxy loop, so we are testing this branch on our prod, 10000 clients to proxy, I can do a feedback then.
Regards, 
Nicolas

**Comment by rofl0r** [comment]
@limbo127: have you been able to do memory usage comparisons ?

**Comment by limbo127** [comment]
after 3 hours, Res memory is 15920 for the tinyproxy.thread ( 3000 clients
// 100 request /s )
for the others tinyproxy.thread proxy memory is ~ 6000  ( < 200 clients )
  , so the memory seems to be increased during time and request, I do not
known if it is a normal behaviour
regards
Nicolas

**Comment by rofl0r** [comment]
15920 would be KBs, right ? so rougly 16 MB? that's not so bad giving that each of the 3000 clients has a separate thread (in the old model, many clients would share a pre-forked process)

**Comment by limbo127** [comment]
Yes

**Comment by limbo127** [comment]
hello,
a lot of ERROR     Aug 22 11:06:32 [29486]: read_buffer: read() failed on
fd 3: Connection reset by peer
ERROR     Aug 22 11:06:33 [29486]: read_buffer: read() failed on fd 3:
Connection reset by peer
ERROR     Aug 22 11:06:38 [29486]: read_buffer: read() failed on fd 7:
Connection reset by peer
ERROR     Aug 22 11:06:45 [29486]: read_buffer: read() failed on fd 5:
Connection reset by peer
ERROR     Aug 22 11:06:52 [29486]: read_buffer: read() failed on fd 5:
Connection reset by peer

perhaps a client issue, but it seems to block tinyproxy thread, i need to
restart tinyproxy, with message : dren: 2 threads still alive!
nicolas

**Comment by rofl0r** [comment]
> it seems to block tinyproxy thread

can you elaborate ? i have no idea what "it" is nor which thread, nor what is being blocked.

**Comment by limbo127** [comment]
I'm sorry, I have not more debug. I just need to kill and restart
tinyproxy, it seems it does not answer to request.
nicolas

**Comment by rofl0r** [comment]
> it does not answer to request

is that new ? it seems you were quite happy with this branch a couple weeks ago.
if so, what changed in your setup?

**Comment by limbo127** [comment]
Yes, i think it's working better than standard tinyproxy.
I 'm trying to reproduce

**Comment by riston** [comment]
What is the status of this branch? I made a comparison between the current stable version and this branch and found that this solution works without throwing connection timeouts and connection refused errors. The current stable build has some unexpected behaviour when servers are under load.

Config I used (for the current stable build):
MaxClients: 100, MinSpareServers: 5, MaxSpareServers: 20

**Comment by rofl0r** [comment]
> What is the status of this branch

it's quite complete and master will be switched to this branch soon. just need to find time to revise the SIGHUP config reloading system which could potentially interfere in unexpected ways with the running threads.

**Comment by limbo127** [comment]
Hello,
our tests shows us that's thread tinyproxy crash sometimes, but no log at
this time
regards,
Nicolas Prochazka

**Comment by limbo127** [comment]
Hello, 
tinyproxy does not proces request anymore, after some times
ERROR     Oct 03 08:20:34 [2053]: opensock: Could not retrieve info for https  
ERROR     Oct 03 08:21:50 [2053]: read_buffer: read() failed on fd 3: Connection reset by peer

Regards, 
Nicolas

**Comment by rofl0r** [comment]
> tinyproxy does not proces request anymore, after some times

after how much time?

can you maybe post contents of /proc/$pid/status when this happens, where $pid is tinyproxy's pid ?

**Comment by rofl0r** [comment]
merged as 69c86b9...cd005a9. this branch is now the new master branch targetting 1.11.0, master has been renamed to tp-1.10.x and will only receive bugfixes.

**Comment by talishka** [comment]
I'm also having random read_buffer: read() failed on fd 8: Connection reset by peer, is a fixed newer version outhere? working on ubuntu 18.04, tinyproxy 1.8.4

**Comment by rofl0r** [comment]
@talishka: in order to get the benefits of this branch you need to compile git master from source. there is no release containing the changes yet. if you have further questions/issues, please open a new issue here, thanks.

**Pull request closed without merging**
